mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from django.conf import settings
from django.contrib.staticfiles.views import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('recomm.urls')),
    url(r'^static/(?P<path>.*)$', serve, kwargs={'insecure':True}),
    url(r'^open/', include('open.urls')),
]

open/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.open_query_input, name='open_query_input'),
	url(r'^playlist/(?P<pk>[0-9]+)/$', views.open_get_playlist, name='open_get_playlist')
]

recomm/urls.py
from django.conf.urls import url
from . import views
# from library.views import UpdateThing

urlpatterns = [
	url(r'^$', views.query_input, name='query_input'),
	url(r'^playlist/(?P<pk>[0-9]+)/$', views.get_playlist, name='get_playlist'),
	url(r'^playlist/ending/$', views.ending, name='ending')

]

open/models.py
from django.db import models
from django.utils import timezone
from likert_field.models import LikertField
from django.contrib.auth.models import User

class QueryModel(models.Model):
	title = models.CharField(max_length=200)
	user = models.CharField(max_length=20)
	created_date = models.DateTimeField(default=timezone.now)

class SurveyModel(models.Model):
	q1 = LikertField('음악들이 내가 입력한 주제와 잘 부합하였다.', blank=False)
	q2 = LikertField('음악들의 주제가 서로 일관성이 있었다.', blank=False)
	q3 = LikertField('음악들이 나의 니즈를 잘 반영하였다.', blank=False)
	q4 = LikertField('이번에 새롭에 듣게 된 음악들이 있었다.', blank=False)
	q5 = LikertField('이 웹사이트를 주변 사람들에게 추천하겠다.', blank=False)
	user = models.CharField(max_length=20)
	created_date = models.DateTimeField(default=timezone.now)
	user_input = models.CharField(max_length=200)
	user_output = models.CharField(max_length=200)

recomm/models.py
from django.db import models
from django.utils import timezone
from likert_field.models import LikertField
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
# from django import forms

class QueryModel(models.Model):
	email = models.CharField(max_length=200, blank=False)
	male = models.CharField(max_length=5, blank=True)
	female = models.CharField(max_length=5, blank=True)
	birth = models.CharField(max_length=10, blank=False)

	user = models.CharField(max_length=100)
	created_date = models.DateTimeField(default=timezone.now)

# class SurveyModel(models.Model):
# 	checkbox_inline = models.TypedChoiceField(
#     label=_('Checkbox Inline'),
#     widget=models.CheckboxSelectMultiple,
#     choices=((1, 'Inline 1',), (2, 'Inline 2',), (3, 'Inline 3',), (4, 'Inline 4',),)
# )
class SurveyModel(models.Model):
	# q1 = models.CharField(max_length=5, blank=True)
	# q2 = models.CharField(max_length=5, blank=True)
	# q3 = models.CharField(max_length=5, blank=True)
	q1_1_0 = LikertField(blank=False)

	q2_1_1 = models.CharField(max_length=5, blank=True)
	q2_1_2 = models.CharField(max_length=5, blank=True)
	q2_1_3 = models.CharField(max_length=5, blank=True)
	# q2_1_4 = models.CharField(max_length=5, blank=True)
	# q2_1_5 = models.CharField(max_length=5, blank=True)

	q3_1_1 = models.CharField(max_length=5, blank=True)
	q3_1_2 = models.CharField(max_length=5, blank=True)
	q3_1_3 = models.CharField(max_length=5, blank=True)
	# q3_1_4 = models.CharField(max_length=5, blank=True)
	# q3_1_5 = models.CharField(max_length=5, blank=True)
	###
	q1_2_0 = LikertField(blank=False)

	q2_2_1 = models.CharField(max_length=5, blank=True)
	q2_2_2 = models.CharField(max_length=5, blank=True)
	q2_2_3 = models.CharField(max_length=5, blank=True)
	# q2_2_4 = models.CharField(max_length=5, blank=True)
	# q2_2_5 = models.CharField(max_length=5, blank=True)

	q3_2_1 = models.CharField(max_length=5, blank=True)
	q3_2_2 = models.CharField(max_length=5, blank=True)
	q3_2_3 = models.CharField(max_length=5, blank=True)
	# q3_2_4 = models.CharField(max_length=5, blank=True)
	# q3_2_5 = models.CharField(max_length=5, blank=True)
	###
	q1_3_0 = LikertField(blank=False)

	q2_3_1 = models.CharField(max_length=5, blank=True)
	q2_3_2 = models.CharField(max_length=5, blank=True)
	q2_3_3 = models.CharField(max_length=5, blank=True)
	# q2_3_4 = models.CharField(max_length=5, blank=True)
	# q2_3_5 = models.CharField(max_length=5, blank=True)

	q3_3_1 = models.CharField(max_length=5, blank=True)
	q3_3_2 = models.CharField(max_length=5, blank=True)
	q3_3_3 = models.CharField(max_length=5, blank=True)
	# q3_3_4 = models.CharField(max_length=5, blank=True)
	# q3_3_5 = models.CharField(max_length=5, blank=True)
	###
	q1_4_0 = LikertField(blank=False)

	q2_4_1 = models.CharField(max_length=5, blank=True)
	q2_4_2 = models.CharField(max_length=5, blank=True)
	q2_4_3 = models.CharField(max_length=5, blank=True)
	# q2_4_4 = models.CharField(max_length=5, blank=True)
	# q2_4_5 = models.CharField(max_length=5, blank=True)

	q3_4_1 = models.CharField(max_length=5, blank=True)
	q3_4_2 = models.CharField(max_length=5, blank=True)
	q3_4_3 = models.CharField(max_length=5, blank=True)
	# q3_4_4 = models.CharField(max_length=5, blank=True)
	# q3_4_5 = models.CharField(max_length=5, blank=True)
	###
	q1_5_0 = LikertField(blank=False)

	q2_5_1 = models.CharField(max_length=5, blank=True)
	q2_5_2 = models.CharField(max_length=5, blank=True)
	q2_5_3 = models.CharField(max_length=5, blank=True)
	# q2_5_4 = models.CharField(max_length=5, blank=True)
	# q2_5_5 = models.CharField(max_length=5, blank=True)

	q3_5_1 = models.CharField(max_length=5, blank=True)
	q3_5_2 = models.CharField(max_length=5, blank=True)
	q3_5_3 = models.CharField(max_length=5, blank=True)
	# q3_5_4 = models.CharField(max_length=5, blank=True)
	# q3_5_5 = models.CharField(max_length=5, blank=True)
	###
	q1_6_0 = LikertField(blank=False)

	q2_6_1 = models.CharField(max_length=5, blank=True)
	q2_6_2 = models.CharField(max_length=5, blank=True)
	q2_6_3 = models.CharField(max_length=5, blank=True)
	# q2_6_4 = models.CharField(max_length=5, blank=True)
	# q2_6_5 = models.CharField(max_length=5, blank=True)

	q3_6_1 = models.CharField(max_length=5, blank=True)
	q3_6_2 = models.CharField(max_length=5, blank=True)
	q3_6_3 = models.CharField(max_length=5, blank=True)
	# q3_6_4 = models.CharField(max_length=5, blank=True)
	# q3_6_5 = models.CharField(max_length=5, blank=True)

	# q1_1 = models.CharField(max_length=5, blank=False)
	# q1_1 = models.CharField(max_length=5, blank=False)
	# q1_1 = models.CharField(max_length=5, blank=False)

	## likert
	# q1_1 = LikertField(blank=False)
	# # q2_1 = LikertField(blank=False)
	# q1_2 = LikertField(blank=False)
	# # q2_2 = LikertField(blank=False)
	# q1_3 = LikertField(blank=False)
	# # q2_3 = LikertField(blank=False)
	# q1_4 = LikertField(blank=False)
	# # q2_4 = LikertField(blank=False)
	# q1_5 = LikertField(blank=False)
	# # q2_5 = LikertField(blank=False)
	# q1_6 = LikertField(blank=False)
	# # q2_6 = LikertField(blank=False)
	# q1_7 = LikertField(blank=False)
	# # q2_7 = LikertField(blank=False)
	# q1_8 = LikertField(blank=False)
	# # q2_8 = LikertField(blank=False)
	# q1_9 = LikertField(blank=False)
	# q2_9 = LikertField(blank=False)
	# q1_10 = LikertField(blank=False)
	# q2_10 = LikertField(blank=False)

	user = models.CharField(max_length=100)
	user_ip = models.CharField(max_length=20)
	created_date = models.DateTimeField(default=timezone.now)
	user_input = models.CharField(max_length=200)
	user_output = models.CharField(max_length=200)

recomm/forms.py
from django import forms
from .models import QueryModel
from .models import SurveyModel


class QueryForm(forms.ModelForm):
	class Meta:
		model = QueryModel
		fields = ('email', 'male', 'female', 'birth',)

class SurveyForm(forms.ModelForm):
	class Meta:
		model = SurveyModel
		# fields = ()
		# fields = ('q1','q2', 'q3',)
		# fields = ('q1_1', 'q2_1','q1_2', 'q2_2','q1_3', 'q2_3','q1_4', 'q2_4',)
		fields = ('q1_1_0',\
		'q2_1_1','q2_1_2','q2_1_3',\
		#'q2_1_4','q2_1_5',\
		'q3_1_1','q3_1_2','q3_1_3',\
		#'q3_1_4','q3_1_5', \
		'q1_2_0',\
		'q2_2_1','q2_2_2','q2_2_3',\
		#'q2_2_4','q2_2_5',\
		'q3_2_1','q3_2_2','q3_2_3',\
		#'q3_2_4','q3_2_5', \
		'q1_3_0',\
		'q2_3_1','q2_3_2','q2_3_3',\
		#'q2_3_4','q2_3_5',\
		'q3_3_1','q3_3_2','q3_3_3',\
		#'q3_3_4','q3_3_5',
		'q1_4_0',\
		'q2_4_1','q2_4_2','q2_4_3',\
		#'q2_4_4','q2_4_5',\
		'q3_4_1','q3_4_2','q3_4_3',\
		#'q3_4_4','q3_4_5',\
		'q1_5_0',\
		'q2_5_1','q2_5_2','q2_5_3',\
		#'q2_5_4','q2_5_5',\
		'q3_5_1','q3_5_2','q3_5_3',\
		#'q3_5_4','q3_5_5', \
		'q1_6_0',\
		'q2_6_1','q2_6_2','q2_6_3',\
		# 'q2_6_4','q2_6_5',
		'q3_6_1','q3_6_2','q3_6_3',) #'q3_6_4','q3_6_5', )

recomm/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone
from django.utils.encoding import force_str
from .models import QueryModel, SurveyModel
from .forms import QueryForm, SurveyForm
from .engines import engines
from ipware.ip import get_ip

import requests
import random
from urllib.parse import urlencode, parse_qs

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def query_input(request):
    if request.method == "POST":
        form = QueryForm(request.POST)
        if form.is_valid():
            query = form.save(commit=False)
            query.user = get_client_ip(request)
            query.save()
            response = redirect('get_playlist', pk=query.pk)
            response.set_cookie('username_', urlencode({'id':form.cleaned_data['email']}))
            return response
    else:
    	form = QueryForm()

    response = render(request, 'recomm/index.html', {'form': form})
    # try:
    #     counter = request.COOKIES.get('counter')
    # except NoneType:
    response.set_cookie('counter', 0)
    # print("set query")
    return response


# def store(*values):
#     store.values = values or store.values
#     return store.values
#
#
# def store_list(values):
#     # global x
#     return x.append(values)
#
# def get_store_list():
#     return x

def get_playlist(request, pk):
    if request.method == "POST":
        form = SurveyForm(request.POST)
        if form.is_valid():
            print("form is valid")
            # store_list(pk)
            survey = form.save(commit=False)
            survey.user_ip = get_client_ip(request)
            temp_u = request.COOKIES.get('username_')
            survey.user = parse_qs(temp_u)['id'][0]
            # last_query, last_query_playlist = store()
            temp_q = request.COOKIES.get('query')
            last_query = parse_qs(temp_q)['id'][0]

            last_query_playlist = request.COOKIES.get('query_playlist')
            survey.user_input = last_query
            survey.user_output = last_query_playlist
            survey.save()

            response = redirect('get_playlist', pk=survey.pk)

            counter = int(request.COOKIES.get('counter'))+1

            if counter < 3:
                response.set_cookie('counter', counter)
            else:
                response.delete_cookie('counter')
                response = redirect('ending')

            return response
        else:
            response = redirect('get_playlist', pk=10000)
            return response
    else:
        counter = int(request.COOKIES.get('counter'))
        print(counter)
        query = engines.get_from_test_set(counter)
        print(query)
        algo_result, _ = engines.get_playlist_by_query(query, 2)
        gt_result = engines.get_gt_playlist_by_query(query)
        cosim_result = engines.get_cosim_playlist_by_query(query)

        query_playlist= [(x, 'a') for x in algo_result] \
                        + [(x,'g') for x in gt_result] \
                        + [(x,'c') for x in cosim_result]
        random.shuffle(query_playlist)
        # print(query_playlist)
        # store(query, query_playlist)

        songs_url_list = []
        for song_id, label in query_playlist:
            # print(song_id)
            song_url = "http://music.bugs.co.kr/newPlayer/secureUrl?track_id=%d&format=aac_128" % int(song_id)
            r_song_url = requests.get(url=song_url)

            song_meta = "http://music.bugs.co.kr/player/track/%d" % int(song_id)
            r_song_meta = requests.get(url=song_meta)
            meta_json = r_song_meta.json()['track']

            songs_url_list.append((meta_json['track_title'], meta_json['artist_disp_nm'], r_song_url.json()['secureUrl'], label))

        form = SurveyForm()
        # t = loader.get_template('recomm/playlist.html')
        # c = {'query': query, 'query_playlist': songs_url_list, 'form': form}
        response = render(request, 'recomm/playlist.html', {'query': query, 'query_playlist': songs_url_list, 'form': form, 'counter':int(10-(counter+1))})
        # print(query)
        # response = HttpResponse(t.render(c, request))
        response.set_cookie('query', urlencode({'id':query}))
        response.set_cookie('query_playlist', query_playlist)

    return response


def ending(request):
    response = render(request, 'recomm/ending.html')
    return response

recomm/templates/recomm/base.html
{% load staticfiles %}
{% load static %}

<html>
    <head>
        <title>딥 브금플레이어</title>
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="http://vjs.zencdn.net/5.8.8/video-js.css" type="text/css">
        <link rel="stylesheet" href="{% static 'css/video-js-custom.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'likert/bootstrap-star-rating/css/star-rating.min.css' %}" type="text/css">
        <script src="http://vjs.zencdn.net/5.8.8/video.js"></script>
        <script src="{% static 'likert/bootstrap-star-rating/js/star-rating.min.js' %}" type="text/javascript"></script>
        <link rel="stylesheet" href="{% static 'css/sticky-footer.css' %}" type="text/css">


    </head>

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <div class="page-header">
                        <h1><a href="/" style="color:#777;"><center>딥 브금플레이어</a></h1>
                    </div>
                </div>
            </div>

            {% block content %}
            {% endblock %}
        </div>

        <!-- <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <span><a href="http://hcc.snu.ac.kr" style="color:#777;">서울대학교 인간중심컴퓨팅연구실</a></span>
                        <span style="float:right; color:#777;">jinhanchoi /at/ snu.ac.kr</span>
                    </div>
                </div>
            </div>
        </footer> -->


        {% block scripts %}
        {% endblock %}

    </body>
</html>

recomm/templates/recomm/ending.html
{% extends 'recomm/base.html' %}
{% load static %}


{% block content %}
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">

		<!-- <form method="POST" class="query-form">{% csrf_token %}
			<div class="input-group">
				<input type="text" class="form-control" name="title" id="id_title" placeholder="예) 여행가고 싶을 때 들으면 좋은 노래, 지친 나를 위로하는 음악,..."/>
				<span class="input-group-btn">
					<button class="btn btn-success" type="submit">플레이리스트 만들기</button>
				</span>
			</div>
		</form> -->
		<!-- <div class="site-wrapper">

      <div class="site-wrapper-inner"> -->

        <!-- <div class="cover-container">
		<div class="inner cover"> -->
	<h1 class="cover-heading">감사합니다.</h1>
	<p class="lead" style="float:right; color:#777;"> 긴 시간동안 성실하게 참여해주셔서 감사합니다. 실험 중 불편하셨던 일이나 궁금한 내용이 있으시면 jinhanchoi /at/ snu.ac.kr 문의해주세요. 고맙습니다. </p>
	<p class="lead">
		<a href="#" class="btn btn-lg btn-default">처음으로 돌아가기</a>
	</p>
</div>
	</div>
</div><!-- /row -->
<!-- </div>
</div> -->
<!-- </div>
</div> -->

{% endblock %}

recomm/templates/recomm/index.html
{% extends 'recomm/base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
	    <p class="lead">지금 어떤 음악을 듣고 싶으세요?</p>
			<p> 안녕하세요. 서울대학교 인간중심컴퓨팅연구실입니다. 우리는 자연어 기반 음악 검색 서비스를 만들고 있습니다. 본 웹페이지는 우리의 음악 검색 서비스의 평가를 위해 만들어졌습니다.</p>
			<p> 만약 여러분이 실험에 참여하시게 되면, 제시되는 플레이리스트 제목에 대해 추천된 노래를 들어보면서 각각의 노래를 평가하게 됩니다. 하단의 '평가보내기' 버튼을 누르면 다음 플레이리스트 제목으로 넘어가고, 총 10개의 플레이리스트 제목을 평가해주시면 됩니다. </p>
			<p> 실험 소요시간은 약 한 시간입니다. 실험에 참여해주시는 분들께 추첨을 통해 스타벅스 아메리카노 교환권을 드립니다. 참여를 원하시면 이메일, 성별, 나이를 입력하시고 '실험 시작' 버튼을 눌러주세요. 고맙습니다 :) </p>
			<p> Mac에서는 Safari, Windows에서는 Internet Explorer을 이용해주세요.</p>
	</div>
</div>

<div class="row">
	<br>
	<div class="col-xs-4 col-xs-offset-2">
		<form method="POST" class="query-form">{% csrf_token %}
			<div class="form-group">
				<label for="exampleInputName2">이메일</label>
				<input type='text' class="form-control" name="email" id="id_email" placeholder="jinhanchoi@snu.ac.kr">
			</div>
			<div class="form-group">
				<label for="exampleInputName2">성별</label><br>
				<label class="radio-inline">
  				<input type="radio" name="male" id="id_male" value="m"> 남
				</label>
				<label class="radio-inline">
  				<input type="radio" name="female" id="id_female" value="f"> 여
				</label>
			</div>
			<div class="form-group">
				<label for="exampleInputName2">나이</label>
				<input type='text' class="form-control" name="birth" id="id_birth" placeholder="태어난 연도를 입력해주세요. (예: 1987, 2002) ">
			</div>
				<!-- <span class="input-group-btn"> -->
			<button class="btn btn-success" type="submit">실험 시작</button>
				<!-- </span> -->
			</div>

		</form>
	</div>
</div>
<!-- <hr /> -->
<div class="row">
<br><br><br>
</div>

<div class="row" style="color:#777;">
	<div class="col-xs-8 col-xs-offset-2">
		<p> 노래가 재생되지 않을 때 Adobe Flash Player 설정을 확인해야 합니다.</p>
		<ul class="list-unstyled"> Mac Safari
		<li> 1. Safari > 환경설정 > 보안 > 플러그인 설정 > Adobe Flash Player </li>
		<li> 2. 147.47.123.183 > 드랍다운메뉴에서 '켬'' 선택 > 완료 </li>
		<li> 만약, 1번에서 Adobe Flash Player가 없다면  <a href=https://get.adobe.com/kr/flashplayer/otherversions/>여기</a>로 이동한 뒤, Mac for Safari and Firefox 선택하여 설치 후 재시도 </li>
		</ul>
		<!-- <ul class="list-unstyled"> Windows Chrome
		<li> 1. 주소입력창 왼편의 느낌표를 클릭 </li>
		<li> 2. '플래시'에서 '허용'을 선택 </li>
		</ul> -->
	</div>
</div>


{% endblock %}

recomm/templates/recomm/playlist.html
{% extends 'recomm/base.html' %}
{% load static %}

{% block content %}

	<div class="row">
		<div class="col-sm-7 col-sm-offset-1">
	    <h3>{{ query.title }}</h3>
		</div>
	</div>

	<form method="POST" class="survey-form">{% csrf_token %}
	{% for title, artist, songUrl, label in query_playlist %}
	<div class="row">
		<br><br>
		<div class="col-sm-4 col-sm-offset-2">
			<h4></h4>
			<!-- <h4>{{ title }}<small> | {{ artist }} </small></h4> -->
			<audio id="query-playlist-{{ forloop.counter }}" class="video-js vjs-default-skin" data-setup='{ "controls": true, "preload": "auto" }' style="background-color:white; width:80%; height:3%; margin-bottom:2%; position:relative;">
				<source src={{ songUrl }} type="rtmp/mp4">
				</audio>
		</div>

		<div class="col-sm-4">
			<div class="row">
				<label class="control-label" ><h4>1. 플레이리스트 제목에 적합한 노래인가요? </h4></label>
				<input type="text" class="likert-field" name="q1_{{ forloop.counter }}_0" id="id_q1_{{ forloop.counter }}_0" />
			</div>

			<div class="row">
				<label class="control-label" ><h4>2. 적합하다고 생각한 이유를 모두 골라주세요. </h4></label>
				<div class="form-inline">
					<label class="checkbox"> <input type="checkbox" name="q2_{{ forloop.counter }}_1" id="id_q2_{{ forloop.counter }}_1" value="1" ><small> 내용 </small></h4></label>
	 				<label class="checkbox"> <input type="checkbox" name="q2_{{ forloop.counter }}_2" id="id_q2_{{ forloop.counter }}_2" value="2" ><small> 분위기 </small></h4></label>
					<label class="checkbox"> <input type="checkbox" name="q2_{{ forloop.counter }}_3" id="id_q2_{{ forloop.counter }}_3" value="3" ><small> 보기 없음 </small></h4></label>
					<!-- <label class="checkbox"> <input type="checkbox" name="q2_{{ forloop.counter }}_4" id="id_q2_{{ forloop.counter }}_4" value="4" ><small> 멜로디 </small></h4></label>
					<label class="checkbox"> <input type="checkbox" name="q2_{{ forloop.counter }}_5" id="id_q2_{{ forloop.counter }}_5" value="5" ><small> 보기 없음 </small></h4></label> -->
				</div>
			</div>

			<div class="row">
				<label class="control-label" ><h4>3. 적합하지 않다고 생각한 이유를 모두 골라주세요. </h4></label>
				<div class="form-inline">
					<label class="checkbox"> <input type="checkbox" name="q3_{{ forloop.counter }}_1" id="id_q3_{{ forloop.counter }}_1" value="1" ><small> 내용 </small></h4></label>
	 				<label class="checkbox"> <input type="checkbox" name="q3_{{ forloop.counter }}_2" id="id_q3_{{ forloop.counter }}_2" value="2" ><small> 분위기 </small></h4></label>
					<label class="checkbox"> <input type="checkbox" name="q3_{{ forloop.counter }}_3" id="id_q3_{{ forloop.counter }}_3" value="3" ><small> 보기 없음 </small></h4></label>
					<!-- <label class="checkbox"> <input type="checkbox" name="q3_{{ forloop.counter }}_4" id="id_q3_{{ forloop.counter }}_4" value="4" ><small> 멜로디 </small></h4></label>
					<label class="checkbox"> <input type="checkbox" name="q3_{{ forloop.counter }}_5" id="id_q3_{{ forloop.counter }}_5" value="5" ><small> 보기 없음 </small></h4></label> -->
				</div>
			</div>
		</div>

	</div>
	<!-- <hr /> -->
	{% endfor %}
	<div class="row">
		<br>
		<div class="col-sm-4 col-sm-offset-2">
		</div>
		<div class="col-sm-4">
			<button class="btn btn-success btn pull-right" type="submit">평가 보내기 <small>( {{ counter }}번 남았어요.)</small></button>
		</div>
	</div>
	</form>
</div>

{% endblock %}



{% block scripts %}
<script type="text/javascript" charset="utf-8">
$(document).on('ready', function(){
    $('.likert-field').rating({
        step: 1,
        starCaptions: {1: '전혀 그렇지 않다.', 2: '그렇지 않다.', 3: '보통이다.', 4: '그렇다.', 5: '매우 그렇다.'},
        starCaptionClasses: {1: 'text-danger', 2: 'text-warning', 3: 'text-info', 4: 'text-primary', 5: 'text-success'},
        size: 'sm',
    });
});


</script>
{% endblock %}

recomm/templates/recomm/playlist_back.html
{% extends 'recomm/base.html' %}
{% load static %}
<!-- {% load shuffle %} -->

{% block content %}

	<div class="row">
		<div class="col-sm-7 col-sm-offset-1">
	    <h3>{{ query.title }}</h3>
		</div>
	</div>

	<form method="POST" class="survey-form">{% csrf_token %}
	{% for title, artist, songUrl, label in query_playlist %}
	<div class="row">
		<div class="col-sm-4 col-sm-offset-2">
			<h4>{{ title }}<small> | {{ artist }} </small></h4>
			<audio id="query-playlist-{{ forloop.counter }}" class="video-js vjs-default-skin" data-setup='{ "controls": true, "preload": "auto" }' style="background-color:white; width:80%; height:4%; margin-bottom:2%; position:relative;">
				<source src={{ songUrl }} type="rtmp/mp4">
				</audio>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<label class="control-label" ><h4>1. 큰 제목에 적합한 노래인가요? </h4></label>
				<input type="text" class="likert-field" name="q1_{{ forloop.counter }}" id="id_q1_{{ forloop.counter }}" />
			</div>
			<!-- <div class="row">
				<label class="control-label" for="id_q2_{{ forloop.counter }}"><h4>2. 제목과 분위기가 유사하다. </h4></label>
				<input type="text" class="likert-field" name="q2_{{ forloop.counter }}" id="id_q2_{{ forloop.counter }}" />
			</div> -->
		</div>
	</div><!-- /row -->
	<!-- <hr /> -->
	{% endfor %}
	<div class="row">
		<div class="col-sm-8 col-sm-offset-1">
			<button class="btn btn-success btn pull-right" type="submit">평가 보내기</button>
		</div>
	</div>
</form>

</div>

{% endblock %}



{% block scripts %}

<script type="text/javascript" charset="utf-8">
$(document).on('ready', function(){
    $('.likert-field').rating({
        step: 1,
        starCaptions: {1: '전혀 그렇지 않다.', 2: '그렇지 않다.', 3: '보통이다.', 4: '그렇다.', 5: '매우 그렇다.'},
        starCaptionClasses: {1: 'text-danger', 2: 'text-warning', 3: 'text-info', 4: 'text-primary', 5: 'text-success'},
        size: 'sm',
    });
});


</script>

{% endblock %}